services:
  bot:
    build: .
    environment:
      - mero_token=${mero_token}
      - status_channel=${status_channel}
      - DbUser=${DbUser}
      - DbPassword=${DbPassword}
      - DbConnectionString=jdbc:postgresql://postgres-service:5432/merobot_db
    restart: on-failure:4
    depends_on:
      postgres-service:
        condition: service_healthy

  postgres-service:
    environment:
      - PGUSER=meroron
      - POSTGRES_USER=meroron
      - POSTGRES_PASSWORD=meromeromero
    image: 
      postgres:18
    ports:
      - "8081:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
